<?php

return [
    'shop.name' => 'L - Shop',
    'shop.access_mode' => 'any',
    'shop.enable_signup' => '1',
    'shop.enable_password_reset' => '0',
    'catalog.products_per_page' => '30',
    'shop.currency' => 'rub',
    'shop.currency_html' => '<i class="fa fa-rub"></i>',
    'cart.capacity' => '12',
    'payment.method.robokassa.enabled' => '1',
    'payment.method.robokassa.login' => '',
    'payment.method.robokassa.password1' => '',
    'payment.method.robokassa.algo' => 'sha512',
    'payment.method.robokassa.password2' => '',
    'distributor.name' => 'ShoppingCart',
    'payment.fillupbalance.minsum' => '25',
    'recaptcha.public_key' => '',
    'recaptcha.secret_key' => '',
    'profile.payments_per_page' => '25',
    'api.key' => 'pIkHkipkTKhpeC$ZY)OlnFH$fZWUullL',
    'api.algo' => 'sha512',
    'api.signin.remember_user' => '1',
    'profile.cart_items_per_page' => '25',
    'shop.description' => 'Современная торговая система для Minecraft',
    'shop.keywords' => 'l-shop,магазин,купить,minecraft,маинкрафт',
    'api.enabled' => '0',
    'api.signin.enabled' => '0',
    'api.separator' => ':',
    'api.salt' => '0',
    'payment.method.robokassa.test' => '1',
    'auth.email_activation' => '0',
    'user.enable_change_password' => '1',
    'api.launcher.sashok.auth.error_message' => 'Пользователь с такими данными не найден',
    'api.launcher.sashok.auth.enabled' => '1',
    'api.launcher.sashok.auth.ips_white_list' => '[]',
    'api.launcher.sashok.auth.format' => 'OK:{username}',
    'caching.statistic.ttl' => '60',
    'api.signup.enabled' => '1',
    'caching.pages.ttl' => '3600',
    'news.first_portion' => '15',
    'news.per_page' => '15',
    'caching.news.ttl' => '600',
    'news.enabled' => '1',
    'profile.character.skin.enabled' => '1',
    'profile.character.cloak.enabled' => '1',
    'profile.character.skin.hd' => '1',
    'profile.character.cloak.hd' => '1',
    'profile.character.skin.max_size' => '768',
    'profile.character.cloak.max_size' => '512',
    'shop.sort' => 'name',
    'caching.monitoring.ttl' => '10',
    'monitoring.rcon.timeout' => '1',
    'monitoring.enabled' => '1',
    'auth.signup.redirect' => '1',
    'auth.signup.redirect_url' => 'http://l-shop.ru/servers'
];
